### ISSUE TITLE
Discord Community Server

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker.js#21]
Create and link a Discord community server.

(If you need a moderator for the start and initial setup, I can help)

**Comment by clarkerican** [comment]
What is everyone's take on Slack vs Discord?  I'm happy to help set either one up!

**Comment by damienwebdev** [comment]
We have the Daffodil Discord server https://discord.gg/EcF7XFpr as a temporary server if we need to get stuff done quickly. I don't intend for this to be the forever home of FakerJs though,

**Comment by Shinigami92** [comment]
What's Daffodil? I asked for creating a Faker.js community Discord Server like e.g. we have for Vite or Vue or Quasar

Example:
Vite: https://chat.vitejs.dev <a href="https://chat.vitejs.dev"><img src="https://img.shields.io/badge/chat-discord-blue?style=flat&logo=discord" alt="discord chat"></a>

**Comment by damienwebdev** [comment]
Daffodil is a project that depends on Faker. I was just using it as a temporary server for quick correspondence until we set up a new one.

Use this instead: https://discord.gg/U6JxmrEm for a temporary one.
