### ISSUE TITLE
Change or remove FUNDING.yml?

### ISSUE THREAD

**Issue by BitesizedLion** [faker-js/faker.js#43]
Currently the FUNDING.yml points to Marak (previous author whom is now banned from github).

Maybe this should be updated or removed?

**Comment by Shinigami92** [comment]
https://github.com/faker-js/faker.js/pull/30#issuecomment-1008278307

**Comment by damienwebdev** [comment]
https://github.com/faker-js/faker.js/pull/15#issuecomment-1008174977

**Comment by damienwebdev** [comment]
I'm going to post my thoughts here based upon a discussion that we had when initiating this repository:


> I'm strongly of the opinion that Marak's contributions are valuable and until such time that we actually need funding to maintain this repo, we leave his name in there.
> 
> I'm consciously leaving his name in there for two reasons:
> 
> 1. Marak's apartment burned down, but I'm not knowledgeable enough on the topic to speculate any further. That said, there's no reason to kick someone while they're down.
> 
> 2. Marak has strong opinions on others using his work for a profit that I want to respect.
> 
> 3. Opinion: Marak seems to be going through some tough shit right now that I am neither aware of nor know anything about and I can't imagine taking away funding will make it any easier.
